# Site settings
title: Sitio personal
description: Mi sitio de internet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Quisbert
user_description: Experiencia de más de 10 años en el campo de la informática, estoy seguro que puedo dar soluciones tecnológicas para las necesidades de su empresa, institución o negocio. Entre algunos de los servicios que he trabajado, puedo mencionar los siguientes.
user_title: Software, Web, Maps & Open Source
email: danielquisbert@yandex.com
twitter_username: danielquisbertc
github_username:  danielquisbert
linkedin_username:  danielquisbert

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
